-- Create demo projects
INSERT INTO projects (
  id,
  user_id,
  title,
  description,
  repo_url,
  github_url,
  live_url,
  technologies,
  image_urls,
  stars_count,
  forks_count,
  downloads_count,
  is_private,
  visibility,
  readme_content,
  license,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'React Portfolio Website',
  'A beautiful portfolio website built with React, TypeScript, and Tailwind CSS. Features responsive design, smooth animations, and dark mode support.',
  'https://github.com/demo/react-portfolio',
  'https://github.com/demo/react-portfolio',
  'https://react-portfolio-demo.vercel.app',
  ARRAY['React', 'TypeScript', 'Tailwind CSS'],
  ARRAY['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400'],
  42,
  8,
  156,
  false,
  'public',
  '# React Portfolio Website\n\nA modern, responsive portfolio website built with the latest web technologies.\n\n## Features\n- Responsive design\n- Dark mode support\n- Smooth animations\n- SEO optimized',
  'MIT',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'E-commerce API',
  'Full-featured REST API for an e-commerce platform with authentication, product management, and payment processing.',
  'https://github.com/demo/ecommerce-api',
  'https://github.com/demo/ecommerce-api',
  'https://ecommerce-api-demo.herokuapp.com',
  ARRAY['Node.js', 'Express', 'MongoDB', 'Stripe'],
  ARRAY['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400'],
  28,
  5,
  89,
  false,
  'public',
  '# E-commerce API\n\nA comprehensive REST API for e-commerce applications.\n\n## Features\n- User authentication\n- Product CRUD operations\n- Shopping cart functionality\n- Payment processing with Stripe',
  'MIT',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Task Management App',
  'A collaborative task management application similar to Trello, built with React and Firebase for real-time updates.',
  'https://github.com/demo/task-manager',
  'https://github.com/demo/task-manager',
  'https://task-manager-demo.netlify.app',
  ARRAY['React', 'Firebase', 'Material-UI', 'JavaScript'],
  ARRAY['https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400'],
  67,
  12,
  234,
  false,
  'public',
  '# Task Management App\n\nA collaborative task management application for teams.\n\n## Features\n- Drag and drop interface\n- Real-time collaboration\n- User roles and permissions\n- File attachments',
  'MIT',
  NOW() - INTERVAL '1 week',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Weather Dashboard',
  'Beautiful weather dashboard with interactive maps, forecasts, and location-based weather data using OpenWeatherMap API.',
  'https://github.com/demo/weather-dashboard',
  'https://github.com/demo/weather-dashboard',
  'https://weather-dashboard-demo.vercel.app',
  ARRAY['Vue', 'JavaScript', 'Chart.js', 'CSS'],
  ARRAY['https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=400'],
  35,
  7,
  128,
  false,
  'public',
  '# Weather Dashboard\n\nAn interactive weather dashboard with beautiful visualizations.\n\n## Features\n- Real-time weather data\n- Interactive maps\n- 7-day forecasts\n- Location search',
  'MIT',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Chat Application',
  'Real-time chat application with rooms, private messaging, and file sharing capabilities built with Socket.io.',
  'https://github.com/demo/chat-app',
  'https://github.com/demo/chat-app',
  'https://chat-app-demo.herokuapp.com',
  ARRAY['Node.js', 'Socket.io', 'React', 'MongoDB'],
  ARRAY['https://images.unsplash.com/photo-1577563908411-5077b6dc7624?w=400'],
  91,
  15,
  302,
  false,
  'public',
  '# Real-time Chat Application\n\nA modern chat application with real-time messaging.\n\n## Features\n- Real-time messaging\n- Private and group chats\n- File sharing\n- Emoji support\n- User status indicators',
  'MIT',
  NOW() - INTERVAL '1 week',
  NOW() - INTERVAL '4 days'
);