// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmzuizlafxarkfanlczq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtenVpemxhZnhhcmtmYW5sY3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjY1OTQsImV4cCI6MjA2ODc0MjU5NH0.2GgSQcLAbuv0Kju9m7JBVUo8GYzBFNMeOlCfa2jDTBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});